id: red_light_conflict
map: Town03
weather: ClearNoon
seed: 33
duration: 30.0
fps: 20
fixed_delta_seconds: 0.05
sync_mode: true
no_rendering_mode: false
ego_vehicle: vehicle.tesla.model3
camera:
  width: 1280
  height: 720
  fov: 90
  fps: 20
  preset: driver
events:
  min_event_time_s: 18.0
  voice_lead_time_s: 3.0
  robot_precue_lead_s: 0.5
scenario:
  ego_spawn_index: 8
  background_vehicle_count: 20
  background_walker_count: 12
  ego_brake_frame: 400
  ego_brake_duration_frames: 20
  ego_brake_value: 1.0
  ego_brake_resume_autopilot: true
