suite_id: "P1"
episodes:
  - "P1_T1_merge"
  - "P1_T2_lane_change"
  - "P1_T2_lane_change"
  - "P1_T3_signal_intersection"
  - "P1_T4_unprotected_left"
  - "P1_T5_emergency_yield"
  - "P1_T6_vru_crossing"
